services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: document-management-system:v0.1.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5173:5173
    stdin_open: true 
    tty: true
